"""add partial unique index for current compensation

Revision ID: b7b7b2354964
Revises: 17aae3802be6
Create Date: 2026-06-11 09:55:59.825265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b7b2354964'
down_revision: Union[str, Sequence[str], None] = '17aae3802be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compensations', schema=None) as batch_op:
        batch_op.create_index('uq_current_compensation_per_employee', ['employee_id'], unique=True, sqlite_where=sa.text('effective_to IS NULL'), postgresql_where=sa.text('effective_to IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compensations', schema=None) as batch_op:
        batch_op.drop_index('uq_current_compensation_per_employee', sqlite_where=sa.text('effective_to IS NULL'), postgresql_where=sa.text('effective_to IS NULL'))

    # ### end Alembic commands ###
